### ISSUE TITLE
Could not open socket with Gmail configuration

### ISSUE THREAD

**Issue by michaeli** [emizentech/magento2-custom-smtp#26]
Hi there,

Thank you for the nice extension. I am able to "Send Test Email" (email received successfully), but after "save config" and then send email programmatically in an adminhtml controller "Close" action like below, I got "Could not open socket" error: (no email received)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  Close Action code snippet BEGIN ~~~~~~~~~~~~~~
                /* Send email to customer */
                $customer = $this->customerRepository->getById($ticket->getCustomerId());
                $storeScope = \Magento\Store\Model\ScopeInterface::SCOPE_STORE;
                $transport = $this->transportBuilder
                    ->setTemplateIdentifier($this->scopeConfig->getValue('foggyline_helpdesk/email_template/customer', $storeScope))
                    ->setTemplateOptions(
                        [
                            'area' => \Magento\Framework\App\Area::AREA_ADMINHTML,
                            'store' => $this->storeManager->getStore()->getId(),
                        ]
                    )
                    ->setTemplateVars([
                        'ticket' => $ticket,
                        'customer_name' => $customer->getFirstname()
                    ])
                    ->setFrom([
                        'name' => $this->scopeConfig->getValue('trans_email/ident_general/name', $storeScope),
                        'email' => $this->scopeConfig->getValue('trans_email/ident_general/email', $storeScope)
                    ])
                    ->addTo($customer->getEmail())
                    ->getTransport();
                $transport->sendMessage();
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  Close Action code snippet END  ~~~~~~~~~~~~~~

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  Send gmail Log BEGIN  ~~~~~~~~~~~~~~
Could not open socket
#0 [internal function]: Emizentech\CustomSmtp\Model\Transport->sendMessage()
#1 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#2 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Emizentech\CustomSmtp\Model\Transport\Interceptor->___callParent('sendMessage', Array)
#3 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Emizentech\\Cust...', 'sendMessage', Object(Emizentech\CustomSmtp\Model\Transport\Interceptor), Array, 'customer-sample...')
#4 /var/www/html/m2ll.com/webroot/vendor/magento/module-customer-sample-data/Magento/Framework/Mail/Transport/MailPlugin.php(32): Emizentech\CustomSmtp\Model\Transport\Interceptor->Magento\Framework\Interception\{closure}()
#5 [internal function]: Magento\CustomerSampleData\Magento\Framework\Mail\Transport\MailPlugin->aroundSendMessage(Object(Emizentech\CustomSmtp\Model\Transport\Interceptor), Object(Closure))
#6 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#7 /var/www/html/m2ll.com/webroot/var/generation/Emizentech/CustomSmtp/Model/Transport/Interceptor.php(26): Emizentech\CustomSmtp\Model\Transport\Interceptor->___callPlugins('sendMessage', Array, Array)
#8 /var/www/html/m2ll.com/webroot/app/code/Foggyline/Helpdesk/Controller/Adminhtml/Ticket/Close.php(67): Emizentech\CustomSmtp\Model\Transport\Interceptor->sendMessage()
#9 /var/www/html/m2ll.com/webroot/var/generation/Foggyline/Helpdesk/Controller/Adminhtml/Ticket/Close/Interceptor.php(24): Foggyline\Helpdesk\Controller\Adminhtml\Ticket\Close->execute()
#10 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/App/Action/Action.php(102): Foggyline\Helpdesk\Controller\Adminhtml\Ticket\Close\Interceptor->execute()
#11 /var/www/html/m2ll.com/webroot/app/code/Magento/Backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#12 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#14 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Foggyline\Helpdesk\Controller\Adminhtml\Ticket\Close\Interceptor->___callParent('dispatch', Array)
#15 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Foggyline\\Helpd...', 'dispatch', Object(Foggyline\Helpdesk\Controller\Adminhtml\Ticket\Close\Interceptor), Array, 'adminAuthentica...')
#16 /var/www/html/m2ll.com/webroot/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#17 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Foggyline\Helpdesk\Controller\Adminhtml\Ticket\Close\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#19 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Foggyline\\Helpd...', 'dispatch', Object(Foggyline\Helpdesk\Controller\Adminhtml\Ticket\Close\Interceptor), Array, 'designLoader')
#20 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#21 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Foggyline\Helpdesk\Controller\Adminhtml\Ticket\Close\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#23 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Foggyline\\Helpd...', 'dispatch', Object(Foggyline\Helpdesk\Controller\Adminhtml\Ticket\Close\Interceptor), Array, 'adminMassaction...')
#24 /var/www/html/m2ll.com/webroot/app/code/Magento/Backend/App/Action/Plugin/MassactionKey.php(33): Foggyline\Helpdesk\Controller\Adminhtml\Ticket\Close\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#25 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Foggyline\Helpdesk\Controller\Adminhtml\Ticket\Close\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#27 /var/www/html/m2ll.com/webroot/var/generation/Foggyline/Helpdesk/Controller/Adminhtml/Ticket/Close/Interceptor.php(39): Foggyline\Helpdesk\Controller\Adminhtml\Ticket\Close\Interceptor->___callPlugins('dispatch', Array, Array)
#28 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/App/FrontController.php(55): Foggyline\Helpdesk\Controller\Adminhtml\Ticket\Close\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#29 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#31 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#32 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#33 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#36 /var/www/html/m2ll.com/webroot/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#37 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#38 /var/www/html/m2ll.com/webroot/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#39 /var/www/html/m2ll.com/webroot/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  Send gmail Log END  ~~~~~~~~~~~~~~

Any insight what I did wrong?
Thank you very much,
-Mike

**Comment by srenon** [comment]
@michaeli 

Take a look at https://github.com/magepal/magento2-gmailsmtpapp/issues/30 and https://github.com/magepal/magento2-gmailsmtpapp/issues/15

I guess it hard for @emizentech to support a module that they just cut and paste (line for line) from someone else's hard work, then redistribute as their own
